### ISSUE TITLE
Release News - 3.0 [Pell]

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Playtroy#10]
## Origin of Code Name
`Pell` is the old name of MyPlay, which is the old name of Playtroy.

## Important
We're moved to C# & no longer using the .Net Framework's Settings system.

### `Preview 1`:
 - [ ] Make it's basic functions work.
 - [x] Convert to C#.
 - [x] #9 - Migrate Languages to XML
### `Preview 2`:
 - [ ] #9 - Migrate Playlist to XML
 - [ ] #8 - Add theme & language installer.
### `Preview 3`:
 - [ ] #8 - Improve argument system.
 - [ ] #8 - Improve playlist menu.
 - [ ] #8 - Improve Library.
### `3.0`:
 - [ ] Fix bugs & improve code.
 - [ ] Fix all issues attached to this milestone.
 - [ ] Release packages.
 - [ ] Update web store items.
 - [ ] Update information in [`haltroy.com`](https://haltroy.com).
 - [ ] Announce new update.
